spring: 
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:localdb
    driverClassName: org.h2.Driver
    username : admin 
    password : admin
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql : true