server:
  port: 8080

spring:
  application:
    name: rest-domain-api
  profiles:
    active: local

mybatis:
  type-aliases-package: com.skcc.template.rest.sample_domain.core.domain.entity
  mapper-locations: db/**/*.xml
  configuration:
    map-underscore-to-camel-case: on


logging:
  config: classpath:config/log/logback-${spring.profiles.active}.xml