spring: 
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    # url: jdbc:h2:mem:localdb
    # driverClassName: org.h2.Driver
    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:h2:mem:localdb
    username : admin 
    password : admin
    initialization-mode: always
    data: classpath:db/sample_data_dml.sql
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql : false